version: "3"
services:

  todo-mongodb:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    container_name: todo-mongodb

  todo-backend:
    image: vlad/todo-backend:local
    build: 
      context: ./todo-app/todo-backend
      dockerfile: ./Dockerfile
    depends_on:
      - todo-mongodb
    ports:
      - 4000:4000
    restart: always
    container_name: todo-backend

  todo-frontend:
    image: vlad/todo-frontend:local
    build:
      context: ./todo-app/todo-frontend
      dockerfile: ./Dockerfile
    depends_on:
      - todo-mongodb
      - todo-backend
    ports:
      - 3000:3000
    restart: always
    container_name: todo-frontend