apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-mongodb
  name: todo-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-mongodb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: todo-mongodb
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: todo-app-secrets
                  key: mongo_user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-app-secrets
                  key: mongo_pass
            - name: MONGO_INITDB_DATABASE
              value: todo-app
          image: mongo
          name: todo-mongodb
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}
